name: test
version: 0.0.1
description: A sample command-line application.
#author: Joannis Orlandos <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  mongo_dart: '0.2.10'
